name: test
on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [7, 8]
    steps:
      - uses: actions/checkout@v1
      - name: writeout toolchains.xml file
        uses: ./.github/actions/make-toolchains-xml
        with:
          jdkVersion: ${{ matrix.jdk }}
      - name: create artifactory token
        id: create-artifactory-token
        uses: ./.github/actions/create-artifactory-token
        with:
          admin-username: admin
          admin-password: ${{ secrets.ARTIFACTORY_TOKEN }}
          token-username: ${{ github.actor }}
          url: https://lmmv.jfrog.io/lmmv
      #- name: build docker image
        #run: docker build . --build-arg JDK_VERSION --build-arg CI_PROJECT_URL --tag lmmv-docker.jfrog.io/${{ github.repository }}:${{ matrix.jdk }}-${{ github.sha }} --tag ${{ github.repository }}:${{ matrix.jdk }}-latest
        #env:
          #JDK_VERSION: ${{ matrix.jdk }}
          #CI_PROJECT_URL: https://github.com/${{ github.repository }}
      #- name: login to artifactory
        #run: echo ${{ steps.create-artifactory-token.outputs.artifactory-token }} | docker login -u ${{ github.actor }} --password-stdin lmmv-docker.jfrog.io
      #- run: docker push lmmv-docker.jfrog.io/${{ github.repository }}:${{ matrix.jdk }}-${{ github.sha }}
      #- run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login --username squarebracket --password-stdin
      #- run: docker push ${{ github.repository }}:${{ matrix.jdk }}-latest
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ github.actor }}
          password: ${{ steps.create-artifactory-token.outputs.artifactory-token }}
          registry: lmmv-docker-local.jfrog.io
          auto_tag: true
          build_args: JDK_VERSION=${{ matrix.jdk }},CI_PROJECT_URL=https://github.com/${{ github.repository }}
        env:
          JDK_VERSION_TEST: ${{ matrix.jdk }}
          CI_PROJECT_URL_TEST: https://github.com/${{ github.repository }}

