name: test
on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [7, 8]
    steps:
      - uses: actions/checkout@v1
      - name: writeout toolchains.xml file
        uses: ./.github/actions/make-toolchains-xml
        with:
          jdkVersion: ${{ matrix.jdk }}
      - name: create artifactory token
        id: create-artifactory-token
        uses: ./.github/actions/create-artifactory-token
        with:
          admin-username: admin
          admin-password: ${{ secrets.ARTIFACTORY_TOKEN }}
          token-username: ${{ github.actor }}
          url: https://lmmv.jfrog.io/lmmv
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ github.actor }}
          password: ${{ steps.create-artifactory-token.outputs.artifactory-token }}
          registry: lmmv-docker-local.jfrog.io
          cache: true
          auto_tag: true
