name: test
on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [7, 8]
    steps:
      - uses: actions/checkout@v1
      - name: writeout toolchains.xml file
        uses: ./.github/actions/make-toolchains-xml
        with:
          jdkVersion: ${{ matrix.jdk }}
      - name: Build the Docker image
        run: docker build . --build-arg JDK_VERSION --build-arg CI_PROJECT_URL --tag java-build:$(date +%s)
        env:
          CI_PROJECT_URL: https://github.com/${{ github.repository }}
          JDK_VERSION: ${{ matrix.jdk }}
