name: test
on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [7, 8]
    steps:
      - uses: actions/checkout@v1
      - name: writeout toolchains.xml file
        uses: ./.github/actions/make-toolchains-xml
        with:
          jdkVersion: ${{ matrix.jdk }}
      - name: create artifactory token
        id: create-artifactory-token
        uses: ./.github/actions/create-artifactory-token
        with:
          admin-username: admin
          admin-password: ${{ secrets.ARTIFACTORY_TOKEN }}
          token-username: ${{ github.actor }}
          url: https://lmmv.jfrog.io/lmmv
      - run: docker build . --build-arg JDK_VERSION --build-arg CI_PROJECT_URL --tag lmmv-docker-local.jfrog.io/${{ github.repository }}:${{ github.ref }}
        with:
          JDK_VERSION: ${{ matrix.jdk }}
          CI_PROJECT_URL: https://github.com/${{ github.repository }}
      - run: docker login -u ${{ github.actor }} -p ${{ steps.create-artifactory-token.outputs.artifactory-token }} lmmv-docker-local.jfrog.io
      - run: docker push lmmv-docker-local.jfrog.io/${{ github.repository }}:${{ github.ref }}
      #- uses: jerray/publish-docker-action@master
        #with:
          #username: ${{ github.actor }}
          #password: ${{ steps.create-artifactory-token.outputs.artifactory-token }}
          #registry: lmmv-docker-local.jfrog.io
          #auto_tag: true
          #JDK_VERSION: 

